import Head from "next/head"

import { Button } from "@/components/ui/button"
import { TextArea } from "@/components/ui/text-area"
import { api } from "@/utils/api"
import { useUser } from "@clerk/nextjs"
import type { NextPage } from "next"
import { useRouter } from "next/router"
import { type SubmitHandler, useForm } from "react-hook-form"

const messageFormDefaultValues = {
  message: "",
}

type MessageForm = {
  message: string
}

const ListingView: NextPage = () => {
  const router = useRouter()
  const user = useUser()

  const { data: listing } = api.listings.get.useQuery(
    { listingId: router.query.id as string },
    { enabled: Boolean(router.query.id) },
  )

  const createMessage = api.listings.sendMessage.useMutation()

  const { register, handleSubmit, reset } = useForm<MessageForm>({
    defaultValues: messageFormDefaultValues,
  })

  const onSubmit: SubmitHandler<MessageForm> = (values) => {
    void createMessage
      .mutateAsync({
        message: values.message,
        listingId: listing?.id ?? "",
      })
      .then(() => reset())
  }

  if (!listing) {
    return null
  }

  return (
    <>
      <Head>
        <title>New listing</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1 className="text-center">Items for sale</h1>
        <div className="mx-auto grid max-w-[500px] grid-cols-[1fr_1fr] gap-2 pt-4"></div>
        {user.isSignedIn && (
          <>
            <form onSubmit={handleSubmit(onSubmit)}>
              <TextArea {...register("message", { required: true })} />
              <Button type="submit">Submit</Button>
            </form>
          </>
        )}
      </main>
    </>
  )
}

export default ListingView

//  <p>{items}</p>
//       <Button onClick={addItem}>add</Button>
//       <Button onClick={removeItem}>remove</Button>
