import Head from "next/head"

// import { api } from "@/utils/api"
import { Button } from "@/components/ui/button"
import useCartStore from "./store/store"
import { SignInButton, SignUpButton, useUser } from "@clerk/nextjs"

export default function Home() {
  // const hello = api.example.hello.useQuery({ text: "from tRPC" })
  const { items, addItem, removeItem } = useCartStore()

  const user = useUser()

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        {user.isSignedIn ? (
          <SignUpButton>Sign up</SignUpButton>
        ) : (
          <SignInButton>Sign in</SignInButton>
        )}
        <p>{items}</p>
        <Button onClick={addItem}>add</Button>
        <Button onClick={removeItem}>remove</Button>
      </main>
    </>
  )
}
