import Head from "next/head"

import { api } from "@/utils/api"
import {
  Card,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
} from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import Link from "next/link"

export default function Home() {
  const { data: listings } = api.listings.list.useQuery()
  // const { items, addItem, removeItem } = useCartStore()

  console.log(listings)

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1 className="text-center">Items for sale</h1>
        <div className="mx-auto grid max-w-[500px] grid-cols-[1fr_1fr] gap-2 pt-4">
          {listings?.map((item) => (
            <Card key={item.id} className="pt-4">
              <CardHeader>
                <CardTitle>{item.name}</CardTitle>
                <CardDescription>
                  <p>{item.description}</p>
                </CardDescription>
              </CardHeader>
              <CardContent>
                <p className="mt-2">{item.price}</p>
              </CardContent>
              <CardFooter>
                <Button asChild>
                  <Link href={`/listings/${item.id}`}>Edit</Link>
                </Button>
              </CardFooter>
            </Card>
          ))}
        </div>
      </main>
    </>
  )
}

//  <p>{items}</p>
//       <Button onClick={addItem}>add</Button>
//       <Button onClick={removeItem}>remove</Button>
