import Head from "next/head"

import { Card, CardContent } from "@/components/ui/card"
import { api } from "@/utils/api"

export default function Home() {
  const { data: messages } = api.listings.getMessages.useQuery()

  return (
    <>
      <Head>
        <title>Offers</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1 className="text-center">YourOffers</h1>
        <div className="mx-auto grid max-w-[500px] grid-cols-[1fr_1fr] gap-2 pt-4">
          {messages?.map((message) => (
            <Card key={message.id} className="pt-4">
              <CardContent>
                <p className="mt-2">{message.message}</p>
              </CardContent>
            </Card>
          ))}
        </div>
      </main>
    </>
  )
}
