import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { api } from "@/utils/api"
import Head from "next/head"
import { useRouter } from "next/router"
import { useForm, type SubmitHandler } from "react-hook-form"

type SellItemForm = {
  name: string
  description: string
  price: number
}

const SellAnItem = () => {
  const createListing = api.listings.create.useMutation()
  const router = useRouter()
  const { register, handleSubmit } = useForm<SellItemForm>()

  const onSubmit: SubmitHandler<SellItemForm> = (values) => {
    console.log(values)
    void createListing.mutateAsync(values).then(() => router.push("/"))
  }

  return (
    <>
      <Head>
        <title>Sell an item</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
        <h1>Sell an item</h1>
        <form
          onSubmit={handleSubmit(onSubmit)}
          className="mt-2 flex flex-col gap-3"
        >
          <div>
            <Input
              type="text"
              placeholder="name"
              {...register("name", { required: true })}
            />
          </div>
          <div>
            <Input
              type="text"
              placeholder="description"
              {...register("description", { required: true })}
            />
          </div>
          <div>
            <Input
              type="number"
              step="0.01"
              placeholder="price"
              {...register("price", { required: true, valueAsNumber: true })}
            />
          </div>
          <Button type="submit">Submit</Button>
        </form>
      </main>
    </>
  )
}

export default SellAnItem
